# Generated by Django 5.1.3 on 2025-11-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100)),
                ('period', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
